### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/CRUZER32/code/jam'

### ISSUE THREAD

**Issue by nitehogg** [dart-atom/dart#1165]
Atom fails, when right clicking a project sourced from removable storage.

1. Add project, located on removable storage.
2. Umount storage device
3. Right-click on project
4. See error.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [dart](https://github.com/dart-atom/dart) package 1.0.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Volumes/CRUZER32/code/jam'

```
At fs.js:912

Error: ENOENT: no such file or directory, stat '/Volumes/CRUZER32/code/jam'
    at fs.statSync (fs.js:912:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:280:16)
    at /packages/dart/web/entry.dart.js:49833:44)
    at /packages/dart/web/entry.dart.js:53929:23)
    at /packages/dart/web/entry.dart.js:53938:21)
    at /packages/dart/web/entry.dart.js:75120:37)
    at /packages/dart/web/entry.dart.js:52389:27)
    at Object.Primitives_applyFunctionWithPositionalArguments (/packages/dart/web/entry.dart.js:32142:28)
    at dart._callDartFunction (/packages/dart/web/entry.dart.js:49710:14)
    at Object.shouldDisplay (/packages/dart/web/entry.dart.js:50012:20)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:167:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:100:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:189:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:248:53)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
atom-toolbar 0.1.6 
atom-typescript 11.0.10 
busy-signal 1.4.3 
dart 1.0.1 
file-icons 2.1.14 
hey-pane 1.1.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
node-debugger 1.10.1 
pretty-json 1.6.4 
split-diff 1.5.1 
```

**Comment by rhaidar** [comment]
+1
